name: Generate HTML Index Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run generate-index.js
      run: node public/generate-index.js
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_ACTIONS: 'true'

    - name: Verify generated files
      run: |
        if ! find keenetic -name "Packages" -type f | grep -q .; then
          echo "❌ Error: No Packages files generated!"
          exit 1
        fi
        echo "✅ Index files generated successfully"
        find keenetic -name "Packages" -type f

    - name: Prepare build folder
      run: |
        mkdir -p build
        if [ -f public/index.html ]; then
          cp public/index.html build/
        fi
        cp -r keenetic build/

    - name: Check build contents
      run: |
        echo "📦 Build folder contents:"
        find build -type f | head -20

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: pg_pages
        publish_dir: ./build
        force_orphan: false
        enable_jekyll: false

    - name: Output deployment info
      run: |
        echo "::notice::✅ Deployed to https://ground-zerro.github.io/release/"
        echo "::notice::📄 Packages at https://ground-zerro.github.io/release/keenetic/"
